version: '3'
services:
  antopolis-server:
    build:
      context: .
      dockerfile: Dockerfile
      context: ./
    container_name: antopolis-server
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app-network

networks:
  app-network:
